### ISSUE TITLE
Why device fingerprint will change？

### ISSUE THREAD

**Issue by berwin** [jackspirou/clientjs#2] opened 2015-04-20 10:52 UTC
var client = new ClientJS();
var fingerprint = client.getFingerprint();
console.log(fingerprint); // fingerprint, change will happen

**Comment by jackspirou** [comment] 2015-05-29 21:03
Hi @berwin.  

Does you fingerprint change here: http://clientjs.jacks.io/ ?

**Comment by berwin** [comment] 2015-05-30 05:18
yes

**Comment by berwin** [comment] 2015-05-30 05:18
@jackspirou  yes

**Comment by jackspirou** [comment] 2015-05-30 05:34
I can't seem to reproduce that issue on any of my browsers, or mobile devices.  

Can you let me know what browser/device you are using?

These are the data points that make up your 32bit integer fingerprint, I wonder if any of these are dynamically changing: 

-	user agent
-	screen print
-	color depth
-	current resolution
-	available resolution
-	device XDPI
-	device YDPI
-	plugin list
-	font list
-	local storage
-	session storage
-	timezone
-	language
-	system language
-	cookies
-	canvas print

**Comment by jackspirou** [comment] 2015-06-11 01:50
@berwin haven't heard anything back in a while.  Any further thoughts?

**Comment by berwin** [comment] 2015-06-11 05:16
@jackspirou  I use Chrome ，Here, the fingerprint will change.

**Comment by berwin** [comment] 2015-06-11 05:17
Now is 3647390930

**Comment by jackspirou** [comment] 2015-06-12 23:55
@berwin - given that this seems to be hard to debug, and I can't reproduce the issue, I think this project should have better debugging methods so we can get useful data to work with. I'll keep this issue open and work on something to address this debug issues we are having.

**Comment by jackspirou** [comment] 2015-06-13 01:22
@berwin - your not using PhoneGap right?  That was a problem for #1

**Comment by jackspirou** [comment] 2015-09-13 21:59
@berwin Im going to close this issue out for now, but let me know if you can provide anymore info on the issue you are experiencing and we can open it back up.

**Closed by jackspirou** 2015-09-13 21:59 UTC
Labels: enhancement

**Comment by danmo** [comment] 2018-04-12 19:34
Happened to me on Safari, twice in a day.

**Comment by bastienu** [comment] 2019-02-14 13:59
Same here, on the same day, after 12 hours.

Anything to help ?
