### ISSUE TITLE
Export issue

### ISSUE THREAD

**Issue by lehaBay** [jackspirou/clientjs#17] opened 2015-12-21 19:26 UTC
Hi!

problem is in this line: https://github.com/jackspirou/clientjs/blob/master/src/client.js#L683
in minified version before this line exports = q is executed, q is a UAParser here which is a function.

so typeof exports === 'object' is false here 

so "module.exports = ClientJS;" is never executed so when one require clientjs he has a UAParser instead. 

hope that makes sense

**Comment by jackspirou** [comment] 2015-12-21 20:16
Hi @lehaBay thanks for creating this issue. 

You mean this line in the minified version correct?  https://github.com/jackspirou/clientjs/blob/master/dist/client.min.js#L21

**Comment by jackspirou** [comment] 2015-12-21 20:32
Ah yes... I found it in the original UAParser source:

```JavaScript
if(typeof module!==UNDEF_TYPE&&module.exports){
    exports=module.exports=UAParser
  }
  exports.UAParser=UAParser
```

I wonder if its best to simply remove those lines or remove `typeof exports === 'object'` in the ClientJS source.

Thoughts?

**Comment by lehaBay** [comment] 2015-12-22 06:14
I think typeof exports === 'object' should be replaced with typeof exports  !== "undefined"

but actually there is one more problem. 
there is a line from minified version:
if ("undefined" !== typeof exports)"undefined" !== typeof module && module.exports && (exports = module.exports = q), exports.UAParser = q; else {
    f.UAParser = q;

so, window.UAParser isn't set if 'exports' is defined so this line throws an error: 
e = (new UAParser).getResult();

**Comment by lehaBay** [comment] 2015-12-22 07:36
@jackspirou 

so it works if replace 
e = (new UAParser).getResult(); 
with 
e = (new (window.UAParser||exports.UAParser)).getResult();

and replace typeof exports === 'object' in the ClientJS  with typeof exports !== 'undefined'


and one more thing, looks like library installed using npm is older than one in repository. It doesn't have getCustomFingerprint method

**Comment by jackspirou** [comment] 2015-12-31 02:58
@lehaBay I ended up replacing the minified versions with the regular source code in the vendors directories since those get minified anyway by the `build.sh` bash script. 

After review the commends it looks like the code that was causing the issue is optional so I commented it out.  You can find it here: https://github.com/jackspirou/clientjs/blob/master/src/vendor/ua-parser.js#L866 

As for `exports === 'object'` i took your suggestion and replaced it with `typeof exports !== "undefined"`.  

Also I updated the npm registry with the latest version numbers that also include these changes. 

Let me know what you think and if we still need to make some changes or if we can close this issue.  Thanks!

**Comment by lehaBay** [comment] 2016-01-03 06:25
@jackspirou i'm having this error now "Uncaught ReferenceError: UAParser is not defined", what i mentioned in the comment above resolves this and everything else is fine now

**Comment by jackspirou** [comment] 2016-01-03 06:49
@lehaBay the code you have suggested in the comment above (without markup) is in reference to the minified version. Im glad you got the minified version to work, but really we should be updating the source file, namely `src/client.js` and the vendor file `src/vendor/ua-parser.js` which is why I referenced it above.

**Comment by lehaBay** [comment] 2016-01-03 12:37
@jackspirou ok, i thought it's easy to find this line in the sources. here it is:
https://github.com/jackspirou/clientjs/blob/master/src/client.js#L139

just replace `var parser = new UAParser();` with `var parser = new (window.UAParser||exports.UAParser);`

**Comment by jackspirou** [comment] 2016-01-03 16:03
@lehaBay it wasn't so obvious to me :stuck_out_tongue_winking_eye: 

Thanks for sticking through this issue and helping me get this to work with requirejs.  I don't this project in other large projects much myself, so its great to have give some feedback and fix this issue for others too.  

I made the updates and now we are on [npm clientjs version 0.1.8](https://www.npmjs.com/package/clientjs).  Let me know if we are good on requrejs now :)

**Comment by lehaBay** [comment] 2016-01-04 16:26
@jackspirou Now it's fine, thank you for fixing it, i found another issue with getCustomFingerprint but i'll create a new one because it's not related to this one

**Comment by jackspirou** [comment] 2016-01-04 19:00
@lehaBay Awesome thanks again for you help!

**Closed by jackspirou** 2016-01-04 19:00 UTC
